-- MySQL Script generated by MySQL Workbench
-- Fri Sep 30 13:30:37 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `bengalremedi_app`;



-- -----------------------------------------------------
-- Schema purchase_order
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bengalremedi_app`DEFAULT CHARACTER SET utf8 ;
USE `bengalremedi_app`;

-- -----------------------------------------------------
-- Table `bengalremedi_app`.`bengalremedi_app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bengalremedi_app`.`br_purchase_order` ;



-- -----------------------------------------------------
-- purchase order line item
-- -----------------------------------------------------

DROP TABLE IF EXISTS `bengalremedi_app`.`br_purchase_order_line` ;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- INSERT INTO `bengalremedi_app`.`br_purchase_order` (`po_id`, `order_from`, `order_date`, `po_details_id`) VALUES ('2', '1','1','20' ,'2016-10-03 00:00:00', 'Y');


-- COMPANY DETAILS

DROP TABLE IF EXISTS `bengalremedi_app`.`company` ;





-- DRUG DETAILS
 DROP TABLE IF EXISTS `bengalremedi_app`.`br_drug_details` ;


-- PRODUCT TYPE

DROP TABLE IF EXISTS `bengalremedi_app`.`br_product_type` ;


-- -----------------------------------------------------
-- product list
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bengalremedi_app`.`br_product_list` ;


-- -----------------------------------------------------
-- drug associated with product
-- -----------------------------------------------------

  DROP TABLE IF EXISTS `bengalremedi_app`.`br_drug_prod_associate` ;









